"""
Pharmaceutical and medicinal glossary for English-to-Russian translation.

Contains common pharma/COA terms and their standard Russian translations
to ensure consistency and accuracy in Certificate of Analysis translations.
"""

# Comprehensive pharmaceutical glossary: English -> Russian
PHARMA_GLOSSARY = {
    # Document types and headers
    "Certificate of Analysis": "Сертификат анализа",
    "COA": "Сертификат анализа",
    "Certificate of Compliance": "Сертификат соответствия",
    "Material Safety Data Sheet": "Паспорт безопасности материала",
    "MSDS": "Паспорт безопасности материала",
    "Batch Record": "Протокол серии",
    "Specification": "Спецификация",

    # Product identification
    "Product Name": "Наименование продукта",
    "Trade Name": "Торговое наименование",
    "Generic Name": "Международное непатентованное наименование",
    "INN": "МНН",
    "International Nonproprietary Name": "Международное непатентованное наименование",
    "Batch Number": "Номер серии",
    "Batch No.": "Номер серии",
    "Batch No": "Номер серии",
    "Lot Number": "Номер серии",
    "Lot No.": "Номер серии",
    "Lot No": "Номер серии",
    "Manufacturing Date": "Дата производства",
    "Date of Manufacture": "Дата производства",
    "Expiry Date": "Срок годности",
    "Expiration Date": "Срок годности",
    "Retest Date": "Дата переконтроля",
    "Shelf Life": "Срок хранения",

    # Manufacturer info
    "Manufacturer": "Производитель",
    "Supplier": "Поставщик",
    "Country of Origin": "Страна происхождения",
    "Manufacturing Site": "Производственная площадка",
    "Quality Control": "Контроль качества",
    "Quality Assurance": "Обеспечение качества",
    "QC": "Контроль качества",
    "QA": "Обеспечение качества",
    "Approved by": "Утверждено",
    "Released by": "Выпущено",
    "Authorized Person": "Уполномоченное лицо",

    # Test parameters and methods
    "Test": "Испытание",
    "Test Method": "Метод испытания",
    "Method": "Метод",
    "Result": "Результат",
    "Results": "Результаты",
    "Acceptance Criteria": "Критерии приемлемости",
    "Limit": "Предел",
    "Limits": "Пределы",
    "Specification Limit": "Предел спецификации",
    "Upper Limit": "Верхний предел",
    "Lower Limit": "Нижний предел",
    "Reference Standard": "Стандартный образец",

    # Physical tests
    "Appearance": "Внешний вид",
    "Description": "Описание",
    "Color": "Цвет",
    "Odor": "Запах",
    "Taste": "Вкус",
    "Physical Form": "Физическая форма",
    "Crystal Form": "Кристаллическая форма",
    "Polymorphic Form": "Полиморфная форма",
    "Particle Size": "Размер частиц",
    "Particle Size Distribution": "Распределение частиц по размерам",
    "Bulk Density": "Насыпная плотность",
    "Tapped Density": "Плотность после утряски",
    "Flowability": "Сыпучесть",
    "Solubility": "Растворимость",
    "Melting Point": "Температура плавления",
    "Boiling Point": "Температура кипения",
    "Viscosity": "Вязкость",
    "pH": "pH",
    "Specific Gravity": "Удельная масса",
    "Density": "Плотность",
    "Refractive Index": "Показатель преломления",
    "Optical Rotation": "Оптическое вращение",
    "Specific Rotation": "Удельное вращение",

    # Chemical tests
    "Assay": "Количественное определение",
    "Purity": "Чистота",
    "Potency": "Активность",
    "Content": "Содержание",
    "Active Ingredient": "Действующее вещество",
    "Active Pharmaceutical Ingredient": "Активная фармацевтическая субстанция",
    "API": "АФС",
    "Excipient": "Вспомогательное вещество",
    "Impurities": "Примеси",
    "Related Substances": "Родственные примеси",
    "Degradation Products": "Продукты деградации",
    "Residual Solvents": "Остаточные растворители",
    "Heavy Metals": "Тяжёлые металлы",
    "Elemental Impurities": "Элементные примеси",
    "Residue on Ignition": "Остаток после прокаливания",
    "Sulfated Ash": "Сульфатная зола",
    "Loss on Drying": "Потеря в массе при высушивании",
    "Water Content": "Содержание воды",
    "Moisture Content": "Содержание влаги",
    "Karl Fischer": "Карл Фишер",
    "Organic Impurities": "Органические примеси",
    "Inorganic Impurities": "Неорганические примеси",
    "Specified Impurity": "Идентифицированная примесь",
    "Unspecified Impurity": "Неидентифицированная примесь",
    "Total Impurities": "Сумма примесей",
    "Identification": "Идентификация",
    "Identity": "Подлинность",

    # Analytical methods
    "HPLC": "ВЭЖХ",
    "High Performance Liquid Chromatography": "Высокоэффективная жидкостная хроматография",
    "GC": "ГХ",
    "Gas Chromatography": "Газовая хроматография",
    "TLC": "ТСХ",
    "Thin Layer Chromatography": "Тонкослойная хроматография",
    "UV": "УФ",
    "UV/Vis": "УФ/Вид",
    "Ultraviolet": "Ультрафиолетовый",
    "Infrared": "Инфракрасный",
    "IR": "ИК",
    "FTIR": "ИК-Фурье",
    "NMR": "ЯМР",
    "Nuclear Magnetic Resonance": "Ядерный магнитный резонанс",
    "Mass Spectrometry": "Масс-спектрометрия",
    "MS": "МС",
    "LC-MS": "ЖХ-МС",
    "GC-MS": "ГХ-МС",
    "ICP": "ИСП",
    "ICP-MS": "ИСП-МС",
    "ICP-OES": "ИСП-ОЭС",
    "X-Ray Diffraction": "Рентгеновская дифракция",
    "XRD": "РД",
    "DSC": "ДСК",
    "Differential Scanning Calorimetry": "Дифференциальная сканирующая калориметрия",
    "Titration": "Титрование",
    "Potentiometric Titration": "Потенциометрическое титрование",
    "Conductivity": "Электропроводность",
    "Polarimetry": "Поляриметрия",

    # Microbiological tests
    "Microbial Limits": "Микробиологическая чистота",
    "Microbial Limit Test": "Испытание на микробиологическую чистоту",
    "Total Aerobic Microbial Count": "Общее число аэробных микроорганизмов",
    "TAMC": "ОАКМ",
    "Total Yeast and Mold Count": "Общее число дрожжей и плесневых грибов",
    "TYMC": "ОДПГ",
    "Bacterial Endotoxins": "Бактериальные эндотоксины",
    "Endotoxin": "Эндотоксин",
    "Sterility": "Стерильность",
    "Sterility Test": "Испытание на стерильность",
    "Bioburden": "Микробная нагрузка",
    "Colony Forming Units": "Колониеобразующие единицы",
    "CFU": "КОЕ",
    "E. coli": "E. coli",
    "Salmonella": "Сальмонелла",
    "Staphylococcus aureus": "Staphylococcus aureus",
    "Pseudomonas aeruginosa": "Pseudomonas aeruginosa",
    "Absence": "Отсутствие",
    "Absent": "Отсутствует",
    "Detected": "Обнаружено",
    "Not Detected": "Не обнаружено",
    "LAL Test": "ЛАЛ-тест",

    # Dosage forms
    "Tablet": "Таблетка",
    "Tablets": "Таблетки",
    "Capsule": "Капсула",
    "Capsules": "Капсулы",
    "Injection": "Инъекция",
    "Solution": "Раствор",
    "Suspension": "Суспензия",
    "Ointment": "Мазь",
    "Cream": "Крем",
    "Gel": "Гель",
    "Powder": "Порошок",
    "Granules": "Гранулы",
    "Syrup": "Сироп",
    "Suppository": "Суппозиторий",
    "Lyophilized Powder": "Лиофилизированный порошок",
    "Film-coated Tablet": "Таблетка, покрытая плёночной оболочкой",
    "Film-coated Tablets": "Таблетки, покрытые плёночной оболочкой",
    "Oral Solution": "Раствор для приёма внутрь",
    "Solution for Injection": "Раствор для инъекций",

    # Packaging and storage
    "Storage Conditions": "Условия хранения",
    "Store at": "Хранить при",
    "Room Temperature": "Комнатная температура",
    "Protect from Light": "Защищать от света",
    "Protect from Moisture": "Защищать от влаги",
    "Keep in a Dry Place": "Хранить в сухом месте",
    "Container": "Контейнер",
    "Package": "Упаковка",
    "Primary Packaging": "Первичная упаковка",
    "Secondary Packaging": "Вторичная упаковка",
    "Blister Pack": "Блистерная упаковка",
    "Vial": "Флакон",
    "Ampoule": "Ампула",

    # Units and measurements
    "Not More Than": "Не более",
    "Not Less Than": "Не менее",
    "NMT": "Не более",
    "NLT": "Не менее",
    "Conforms": "Соответствует",
    "Complies": "Соответствует",
    "Does not comply": "Не соответствует",
    "Passes": "Выдерживает",
    "Pass": "Выдерживает",
    "Fail": "Не выдерживает",
    "Within specification": "В пределах спецификации",
    "Out of specification": "Вне спецификации",
    "OOS": "Вне спецификации",
    "mg": "мг",
    "mcg": "мкг",
    "µg": "мкг",
    "mL": "мл",
    "mg/mL": "мг/мл",
    "mg/g": "мг/г",
    "IU": "МЕ",
    "International Unit": "Международная единица",
    "EU/mL": "ЕЭ/мл",
    "Endotoxin Unit": "Единица эндотоксина",

    # Regulatory references
    "USP": "Фармакопея США",
    "EP": "Европейская Фармакопея",
    "BP": "Британская Фармакопея",
    "JP": "Японская Фармакопея",
    "Ph. Eur.": "Европейская Фармакопея",
    "Pharmacopoeia": "Фармакопея",
    "Pharmacopeia": "Фармакопея",
    "GMP": "GMP (Надлежащая производственная практика)",
    "Good Manufacturing Practice": "Надлежащая производственная практика",
    "ICH": "ICH",
    "In-house Method": "Внутренний метод",
    "Compendial Method": "Фармакопейный метод",

    # Stability
    "Stability": "Стабильность",
    "Stability Study": "Исследование стабильности",
    "Accelerated Stability": "Ускоренная стабильность",
    "Long-term Stability": "Долгосрочная стабильность",
    "Intermediate Stability": "Промежуточная стабильность",
    "Dissolution": "Растворение",
    "Dissolution Test": "Испытание растворения",
    "Disintegration": "Распадаемость",
    "Disintegration Test": "Испытание на распадаемость",
    "Friability": "Истираемость",
    "Hardness": "Твёрдость",
    "Uniformity of Dosage Units": "Однородность дозирования",
    "Content Uniformity": "Однородность содержания",
    "Weight Variation": "Отклонение в массе",

    # Common COA result phrases
    "White to off-white powder": "Белый или почти белый порошок",
    "White crystalline powder": "Белый кристаллический порошок",
    "Clear colorless solution": "Прозрачный бесцветный раствор",
    "Clear to slightly opalescent": "Прозрачный до слегка опалесцирующего",
    "Practically insoluble in water": "Практически нерастворим в воде",
    "Freely soluble in water": "Легко растворим в воде",
    "Soluble in water": "Растворим в воде",
    "Slightly soluble in water": "Мало растворим в воде",
    "Sparingly soluble in water": "Умеренно растворим в воде",
    "Positive": "Положительный",
    "Negative": "Отрицательный",
    "Consistent with reference": "Соответствует стандарту",
    "Consistent with standard": "Соответствует стандарту",
    "as is basis": "в пересчёте на исходное вещество",
    "on dried basis": "в пересчёте на сухое вещество",
    "on anhydrous basis": "в пересчёте на безводное вещество",
    "as received": "в исходном виде",
}


def get_glossary_prompt_section() -> str:
    """
    Build a formatted glossary section to include in the translation prompt.
    Returns a string with key pharmaceutical terms and their Russian equivalents.
    """
    lines = []
    for eng, rus in PHARMA_GLOSSARY.items():
        lines.append(f"  \"{eng}\" → \"{rus}\"")
    return "\n".join(lines)


def get_glossary_dict() -> dict:
    """Return the full glossary dictionary."""
    return PHARMA_GLOSSARY.copy()
